name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ github.ref_name }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: make
        run: make
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          tar.exe -acf winux-$tag.zip *.exe
          gh release create "$tag" `
              --repo="$GITHUB_REPOSITORY" `
              --title="${tag#v}" `
              --generate-notes `
              winux-$tag.zip

