name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ github.ref_name }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: make
        run: make
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tar.exe -acf winux-$tag.zip *.exe
          gh release create $env:GITHUB_REF_NAME `
              --repo=$env:GITHUB_REPOSITORY `
              --title=$env:GITHUB_REF_NAME `
              --generate-notes `
              winux-$env:GITHUB_REF_NAME.zip

